# Generated by Django 3.0.8 on 2020-07-14 22:44

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleJournaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitulé', models.CharField(default='', max_length=100)),
                ('nomAuteur', models.CharField(default='', max_length=100)),
                ('maison_edition', models.CharField(default='', max_length=100)),
                ('annéeEdition', models.DateField(default='', max_length=100)),
                ('nombrePages', models.IntegerField()),
                ('type', models.CharField(default='', max_length=100)),
                ('prix', models.IntegerField()),
                ('article', models.FileField(default=None, upload_to='article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitulé', models.CharField(default='', max_length=100)),
                ('nomAuteur', models.CharField(default='', max_length=100)),
                ('maison_edition', models.CharField(default='', max_length=100)),
                ('annéeEdition', models.DateField(default='', max_length=100)),
                ('nombrePages', models.IntegerField()),
                ('type', models.CharField(default='', max_length=100)),
                ('Nbre_tome', models.IntegerField(default=None)),
                ('livre', models.FileField(default='', upload_to='livre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitulé', models.CharField(default='', max_length=100)),
                ('nomAuteur', models.CharField(default='', max_length=100)),
                ('maison_edition', models.CharField(default='', max_length=100)),
                ('annéeEdition', models.DateField(default='', max_length=100)),
                ('nombrePages', models.IntegerField()),
                ('type', models.CharField(default='', max_length=100)),
                ('nombreChapitre', models.IntegerField()),
                ('memoire', models.FileField(default='', upload_to='memoire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100, verbose_name=django.contrib.auth.models.User)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critique', models.TextField(max_length=500, null=True)),
                ('utilisateur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Utilisateur')),
            ],
        ),
    ]
