# Generated by Django 3.0.8 on 2020-07-14 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_compte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='utilisateur',
        ),
        migrations.CreateModel(
            name='Review_memoire',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Review')),
                ('memoire', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Memoire')),
            ],
            bases=('blog.review',),
        ),
        migrations.CreateModel(
            name='Review_livre',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Review')),
                ('livre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Livre')),
            ],
            bases=('blog.review',),
        ),
        migrations.CreateModel(
            name='Review_article',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Review')),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleJournaux')),
            ],
            bases=('blog.review',),
        ),
    ]
