# Generated by Django 3.0.8 on 2020-07-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200715_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_livre',
            name='utilisateur',
        ),
    ]
