# Generated by Django 3.0.8 on 2020-07-18 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200718_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='review_livre',
            name='utilisateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Utilisateur'),
        ),
    ]
