# Generated by Django 3.0.8 on 2020-07-18 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200718_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_livre',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='review',
            name='utilisateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Utilisateur'),
        ),
    ]
