# Generated by Django 3.0.8 on 2020-07-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200718_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='utilisateur',
        ),
    ]
